export const AUTH_REST_ERROR_CODES = {
  INVALID_PAYLOAD: 'ERR_INVALID_PAYLOAD',
  EMAIL_EXISTS: 'ERR_EMAIL_EXISTS',
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'ERR_ACCOUNT_INACTIVE',
  INVALID_TOKEN: 'ERR_INVALID_TOKEN',
  TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
} as const;

export type AuthRestErrorCode = (typeof AUTH_REST_ERROR_CODES)[keyof typeof AUTH_REST_ERROR_CODES];
