export const REST_ERROR_CODES = {
  // Authentication & Session
  INVALID_PAYLOAD: 'ERR_INVALID_PAYLOAD',
  EMAIL_EXISTS: 'ERR_EMAIL_EXISTS',
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'ERR_ACCOUNT_INACTIVE',
  INVALID_TOKEN: 'ERR_INVALID_TOKEN',
  TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',

  // Room & Membership Domain
  ROOM_NOT_FOUND: 'ERR_ROOM_NOT_FOUND',
  FORBIDDEN: 'ERR_FORBIDDEN',
  ROOM_FULL: 'ERR_ROOM_FULL',
  ROOM_LOCKED: 'ERR_ROOM_LOCKED',
  INVITE_EXPIRED: 'ERR_INVITE_EXPIRED',
  INVITE_MAX_USES: 'ERR_INVITE_MAX_USES',
  INVITE_NOT_FOUND: 'ERR_INVITE_NOT_FOUND',
  NOT_ROOM_MEMBER: 'ERR_NOT_ROOM_MEMBER',
  CANNOT_KICK_SELF: 'ERR_CANNOT_KICK_SELF',
} as const;

export type RestErrorCode = (typeof REST_ERROR_CODES)[keyof typeof REST_ERROR_CODES];

// Backward compatibility alias for auth domain
export const AUTH_REST_ERROR_CODES = REST_ERROR_CODES;
export type AuthRestErrorCode = RestErrorCode;
