name: "Semantic PR"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            test
            refactor
            chore
            security
            perf
            docs
          scopes: |
            shared
            backend
            ws
            rest
            auth
            db
            redis
            sync
            ext
            content
            overlay
            web
            env
            monorepo
          requireScope: true
